# Generated by Django 4.1.4 on 2023-03-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0002_alter_spotifytoken_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
